# Generated by Django 5.1.7 on 2026-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_preview', models.TextField(blank=True)),
                ('version_code', models.CharField(blank=True, max_length=32)),
                ('sources_count', models.PositiveSmallIntegerField(default=0)),
                ('backend', models.CharField(default='stub', help_text='stub | openai', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
