# Generated by Django 5.1.7 on 2026-04-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_add_asksemantic_cache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asksemanticcache',
            new_name='rag_asksema_version_60946e_idx',
            old_name='rag_asksem_version_a835bc_idx',
        ),
    ]
