# Generated by Django 5.1.7 on 2026-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postgres_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
