# Generated by Django 5.1.7 on 2026-04-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_study_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('password_hash', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('web', 'Web (Vercel)'), ('android', 'Android (APK)'), ('ios', 'iOS'), ('unknown', 'Desconhecido')], db_index=True, default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conta da app',
                'verbose_name_plural': 'contas da app',
                'ordering': ['-created_at'],
            },
        ),
    ]
