# Generated by Django 5.1.7 on 2026-05-01 03:03

import django.db.models.deletion
from django.db import migrations, models


def seed_learning_groups(apps, schema_editor):
    LearningGroup = apps.get_model("core", "LearningGroup")
    AppUserAccount = apps.get_model("core", "AppUserAccount")
    alunos, _ = LearningGroup.objects.get_or_create(slug="alunos", defaults={"name": "Alunos"})
    LearningGroup.objects.get_or_create(slug="professores", defaults={"name": "Professores"})
    AppUserAccount.objects.filter(learning_group__isnull=True).update(learning_group=alunos)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_app_user_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="appuseraccount",
            name="api_token",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name="CollectiveStudy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("lesson_at", models.DateTimeField(db_index=True)),
                (
                    "allow_external_requests",
                    models.BooleanField(
                        default=True,
                        help_text="Se verdadeiro, utilizadores fora do grupo audiência podem pedir acesso.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collective_studies_authored",
                        to="core.appuseraccount",
                    ),
                ),
                (
                    "audience_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collective_studies",
                        to="core.learninggroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-lesson_at"],
            },
        ),
        migrations.AddField(
            model_name="appuseraccount",
            name="learning_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="core.learninggroup",
            ),
        ),
        migrations.CreateModel(
            name="CollectiveStudyAccessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("accepted", "Aceite"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="core.collectivestudy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collective_access_requests",
                        to="core.appuseraccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("study", "user"), name="uniq_collective_access_study_user")
                ],
            },
        ),
        migrations.RunPython(seed_learning_groups, migrations.RunPython.noop),
    ]
